FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

COPY *.csproj .

COPY /FarmCord .

COPY ./FarmCord/config.json ./bin/Debug/netcoreapp3.1

RUN dotnet restore

RUN dotnet build

RUN dotnet run


