FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

COPY *.csproj .

COPY /FarmCord .

COPY ./FarmCord/config.json .

RUN dotnet restore

RUN dotnet build

RUN cd ..

COPY FarmCord/config.json ./source/bin/Debug/netcoreapp3.1/

RUN dotnet run


